FROM tensorflow/tensorflow:1.5.1-gpu

MAINTAINER Christoph Gebendorfer

RUN pip install sympy && \
    pip install requests && \
    pip install bz2file

RUN apt-get update && \
    apt-get install nano -y

COPY . /etc/tensor2tensor
ENV PYTHONPATH /etc/tensor2tensor
ENV TMP_DIR /tmp/t2t_datagen

RUN mkdir -p /etc/tensor2tensor/data
RUN mkdir -p /etc/tensor2tensor/train
RUN mkdir -p /etc/tensor2tensor/decode
ENV DATA_DIR /etc/tensor2tensor/data
ENV TRAIN_DIR /etc/tensor2tensor/train
ENV DECODE_DIR /etc/tensor2tensor/decode
VOLUME ["/etc/tensor2tensor/data", "/etc/tensor2tensor/train", "/etc/tensor2tensor/decode"]

WORKDIR /etc/tensor2tensor/tensor2tensor/bin

ENTRYPOINT ["/bin/bash"]
